name: workflow-aws-terraform
on:
  workflow_dispatch:
  push:
    branches:
      - master
      #  pull_request:
      #    branches:
      #      - main

jobs:
  CD:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: little-core-labs/install-terraform-action@v2.0.0
        with:
          version: 1.9.8

      - name: Terraform Init
        id: init
        run: |
          terraform init
