name: workflow-aws-terraform
on:
  workflow_dispatch:
    inputs:
      action:
        required: true
        default: 'apply'
        description: 'Select the action'
        type: choice
        options:
        - 'apply'
        - 'destroy'
  push:
    branches:
      - master
      #  pull_request:
      #    branches:
      #      - main

jobs:
  CD:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.9.8

      - name: Terraform apply
        run: |
          terraform init
          terraform plan -var="config_key=config.json"
          terraform ${{ github.event.inputs.action }} -var="config_key=config.json" -auto-approve

      - name: kubectl test
        uses: marcofranssen/setup-kubectl@v0.3.0
        id: kubectl
        with:
          kubectl-version: latest
        run: |
          if [[ ${{ github.event.inputs.action }} == 'apply' ]]; then
            kubectl --kubeconfig ./template/kubeconfig.yaml get all -A
          else
            echo "Skipping kubectl test"
          fi
